## 공통 설정

spring:
  application:
    name: jexon

  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}

jexon:
  file-storage:
    root: ${JEXON_FILE_STORAGE_ROOT:./storage}
    max-file-size: 536870912B
    buffer-size: 65536B
